keyring-backend = "os"          # Name of the keyring backend (os|file|kwallet|pass|test)
keyring-folder = "~/.int3faced" # Path to the keyring folder
mode = "regtest"                # Observer execution mode (mainnet|testnet|regtest)
send-period = "1s"              # Interval for observer to process Tx queue
max-retry-count = 0             # Maximum retries
secrets-file = "./secrets.toml" # File with secrets - rpc accounts, contract details

[int3face]
chain-id             = "int3-test-2"
grpc-url             = "127.0.0.1:9090"
grpc-disable-tls     = true
rpc-url              = "tcp://127.0.0.1:26657"
health-check-period  = "5s"

[api-server]
grpc-port     = 16090
http-enabled  = false
http-port     = 16091

[bitcoin]
rpc-url = "http://127.0.0.1:18343"                                            # Url for the chain specific RPC client
rpc-api-header = ""
last-observed-height = 0                                                      # Last observed block height number, if not set will be requested from the x/bridge
fetch-interval = "30s"                                                        # Interval to scan chain blocks
denom = "btc"                                                                 # Token denom
observed-block-cache-size = 30                                                # Amount of observed blocks to keep in memory
signed-txs-cache-size = 100                                                   # Amount of signed txs to keep in memory

[dogecoin]
rpc-url = "http://127.0.0.1:18332"                                            # Url for the chain specific RPC client
last-observed-height = 0                                                      # Last observed block height number, if not set will be requested from the x/bridge
fetch-interval = "30s"                                                        # Interval to scan chain blocks
denom = "doge"                                                                # Token denom
observed-blocks-cache-size = 30                                               # Amount of observed blocks to keep in memory
signed-txs-cache-size = 100                                                   # Amount of signed txs to keep in memory

[bitcoin-cash]
rpc-url = "http://127.0.0.1:18323"
last-observed-height = 0
fetch-interval = "30s"
denom = "bch"
observed-blocks-cache-size = 30
signed-txs-cache-size = 100

[litecoin]
rpc-url = "http://127.0.0.1:18112"
last-observed-height = 0
fetch-interval = "30s"
denom = "ltc"
observed-blocks-cache-size = 30
signed-txs-cache-size = 100

[ton]
contract-address  = "EQBhbAx2OwLseqKiAfa0E398IuwUJN4ZpbeGHDJ9PCJDD7JI" # Bridge contract address on TON
last-observed-lt  = 34060140000001 # Last observed logical-time
response-timeout  = "30s" # Max wait for TON RPC

[solana]
endpoint            = "https://api.devnet.solana.com"
contract-address    = "Dwq5KPSzvQozX3dUKpQvFqyKETFTjxE5drL2hJ5Z1x49"
tx-fetch-interval   = "10s"
last-tx-scanned     = ""
ntt-claim-enabled   = true
ntt-claim-timeout   = "10m0s"

[[solana.ntt-claimer]]
chain-id                   = "base"
sol-chain-id               = 1
eth-chain-id               = 84532
receive-message-selector   = "f953cec7"
eth-rpc-url                = "https://sepolia.base.org"
eth-max-gas-limit          = 500000
eth-max-gas-price          = 300000
wormhole-rpc-url           = "https://api.testnet.wormscan.io"

[xrpl]
endpoint            = "https://s.altnet.rippletest.net:51234/"
fetch-interval      = "30s"
max-tx-batch-size   = 10
max-scanning-range  = 100
last-observed-height = 8110435

[tss]
bootstrap-peers = [
    "/ip4/65.109.1.30/tcp/16666/p2p/16Uiu2HAm4ETT4eqnU2gPHFST34yfz7BCTviLUvEsoDAbGhKfqkF7",   # 1
    "/ip4/65.108.86.114/tcp/16666/p2p/16Uiu2HAmDG1HyeZc12AGTkrBGCFVmQoUEzNSxCLAgXadQiXJ4yJs", # 2
    "/ip4/5.78.111.245/tcp/16666/p2p/16Uiu2HAm86wV9BD5iXy434XiCRjhPgXgTdjY2Qfqor8vrWGwJNwX",  # 3
] # the peers of the P2P network used to set up the connection
party-port = "16666" # the party's port
rendezvous = "Int3face" # the "meet me here" point
party-timeout = "5m0s" # how long do we wait for the party to form
key-gen-timeout = "5m0s" # how long do we wait the keygen parties to pass messages along
key-sign-timeout = "5m0s" # how long do we wait keysign
pre-param-timeout = "1m0s" # the LocalPreParams generations timeout

[monitoring]
enabled = false # Enable or disable monitoring HTTP server. The list of metrics is presented at https://github.com/Int3facechain/architecture/blob/main/ADR/adr-006-metrics.md
port = "27727"  # TCP port to expose monitoring HTTP server
